#!/bin/sh
#vdr run options file
#path to binary
VDRPRG="/usr/local/bin/vdr"
#options
VDROPTIONS="-w 60 --video=/var/vdr/record --epgfile=/var/vdr/epg.data export VDR_CHARSET_OVERRIDE="ISO-8859-15""
#plugins
VDRPLUGINS="-P vnsiserver -P dvbapi -P streamdev-server -P svdrpservice -P sc"
#parameter comand
VDRCMD="\$VDRPRG \$VDROPTIONS \$VDRPLUGINS \$*"
      
KILL="/usr/bin/killall -q -TERM"
# Detect whether the DVB driver is already loaded
# and return 0 if it *is* loaded, 1 if not:
DriverLoaded()
  {
    return 1
  }
# Load all DVB driver modules needed for your hardware:
LoadDriver()
  {
    return 0
  }
# Unload all DVB driver modules loaded in LoadDriver():
UnloadDriver()
  {
    return 0
  }
# Load driver if it hasn't been loaded already:
if ! DriverLoaded; then
  LoadDriver
fi
while (true) do
  eval "\$VDRCMD"
  if test \$? -eq 0 -o \$? -eq 2; then exit; fi
  echo "`date` reloading DVB driver" $KILL $VDRPRG
  sleep 10
  UnloadDriver
  LoadDriver
  echo "`date` restarting VDR"
done
