#!/bin/bash
### BEGIN INIT INFO
# Provides:          VDR
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Description:       Start, Stop or Restart VDR
### END INIT INFO

#code taken from http://www.vdr-wiki.de/wiki/index.php/HDTV_Installationsanleitung_Ubuntu#.2Fetc.2Finit.d.2Fvdr

case "$1" in
    start)
        echo -n "Starting VDR "
                /usr/local/bin/runvdr > /var/log/vdr.log &
        ;;
    stop)
        echo -n "Shutting down VDR "
                /usr/local/bin/runvdr kill
        ;;
    restart)
        echo -n "Restart VDR "
        $0 stop
        sleep 5
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
exit 0
